; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3usbotg]
platform = espressif32
board = esp32s3box
framework = arduino
monitor_speed = 115200
monitor_dtr = 1
monitor_rts = 0
upload_speed = 921600
board_build.partitions = huge_app.csv
build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -I include
lib_deps =
	ArduinoJson
	adafruit/Adafruit SHT4x Library@^1.0.5
	PubSubClient
	HTTPClient
	adafruit/Adafruit BusIO@^1.14.1
	FastLED
	LedControl
	arduino-libraries/ArduinoMqttClient@^0.1.8
