{
 "title": "Air Quality",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Device",
    "query": "SELECT name FROM Device WHERE revoked=1;"
   }
  ]
 },
 "panels": [
  { "title": "Air Quality", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Air Quality (PM2.5 %)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "dataset": "cmb",
     "rawSql": "SELECT q.value, q.time_unix AS \"time_sec\" FROM cmb.Quality as q INNER JOIN Device AS d ON q.Device_Id = d.id WHERE d.name = '$Device' ORDER BY time_unix DESC "
    }
   ]
  },
  { "title": "SHT41", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "cmb",
     "rawSql": "SELECT s.temperature, s.time_unix AS \"time_sec\" FROM cmb.SHT41 AS s INNER JOIN Device AS d ON s.Device_Id = d.id WHERE d.name = '$Device' ORDER BY time_unix DESC "
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "cmb",
     "rawSql": "SELECT s.humidity, s.time_unix AS \"time_sec\" FROM cmb.SHT41 AS s INNER JOIN Device AS d ON s.Device_Id = d.id WHERE d.name = '$Device' ORDER BY time_unix DESC "
    }
   ]
  },
  { "title": "SPS30", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "PM2.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "dataset": "cmb",
     "rawSql": "SELECT s.mc_2p0, s.time_unix AS \"time_sec\" FROM cmb.SPS30 AS s INNER JOIN Device AS d ON s.Device_Id = d.id WHERE d.name = '$Device' ORDER BY time_unix DESC "
    }
   ]
  }
 ]
}