CREATE DATABASE IF NOT EXISTS `cmb`;

USE `cmb`;
-- MySQL Script generated by MySQL Workbench
-- Mon Dec 15 11:37:20 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Table `cmb`.`Device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cmb`.`Device` (
  `id` VARCHAR(24) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `secret_hex` VARCHAR(255) NOT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `revoked` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cmb`.`SPS30`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cmb`.`SPS30` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mc_1p0` FLOAT NOT NULL,
  `mc_2p0` FLOAT NOT NULL,
  `mc_4p0` FLOAT NOT NULL,
  `mc_10p0` FLOAT NOT NULL,
  `nc_0p5` FLOAT NOT NULL,
  `nc_1p0` FLOAT NOT NULL,
  `nc_2p5` FLOAT NOT NULL,
  `nc_4p0` FLOAT NOT NULL,
  `nc_10p0` FLOAT NOT NULL,
  `typical_particle_size` FLOAT NOT NULL,
  `time_unix` INT NOT NULL,
  `Device_id` VARCHAR(24) NOT NULL,
  PRIMARY KEY (`id`, `Device_id`),
  CONSTRAINT `fk_SPS30_Device1`
    FOREIGN KEY (`Device_id`)
    REFERENCES `cmb`.`Device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_SPS30_Device1_idx` ON `cmb`.`SPS30` (`Device_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `cmb`.`SHT41`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cmb`.`SHT41` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `temperature` FLOAT NOT NULL,
  `humidity` FLOAT NOT NULL,
  `time_unix` INT NOT NULL,
  `Device_id` VARCHAR(24) NOT NULL,
  PRIMARY KEY (`id`, `Device_id`),
  CONSTRAINT `fk_SHT41_Device1`
    FOREIGN KEY (`Device_id`)
    REFERENCES `cmb`.`Device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_SHT41_Device1_idx` ON `cmb`.`SHT41` (`Device_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `cmb`.`Quality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cmb`.`Quality` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` FLOAT NOT NULL,
  `time_unix` VARCHAR(45) NOT NULL,
  `Device_id` VARCHAR(24) NOT NULL,
  PRIMARY KEY (`id`, `Device_id`),
  CONSTRAINT `fk_Quality_Device`
    FOREIGN KEY (`Device_id`)
    REFERENCES `cmb`.`Device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Quality_Device_idx` ON `cmb`.`Quality` (`Device_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `cmb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cmb`.`User` (
  `id` VARCHAR(24) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `mfa_enabled` TINYINT NOT NULL DEFAULT 0,
  `mfa_secret` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
